import { Ingredient } from "@/types";

// Map cuisines to their common ingredients
export const cuisineIngredients: Record<string, string[]> = {
  italian: [
    "tomato",
    "pasta",
    "olive-oil",
    "garlic",
    "basil",
    "mozzarella",
    "parmesan",
    "onion",
    "oregano",
    "bell-pepper",
  ],
  mexican: [
    "tomato",
    "onion",
    "garlic",
    "cilantro",
    "lime",
    "avocado",
    "jalapeno",
    "cumin",
    "black-beans",
    "cheese",
  ],
  chinese: [
    "soy-sauce",
    "ginger",
    "garlic",
    "rice",
    "sesame-oil",
    "green-onion",
    "chicken",
    "mushroom",
    "bell-pepper",
    "rice-vinegar",
  ],
  japanese: [
    "soy-sauce",
    "rice",
    "seaweed",
    "ginger",
    "mirin",
    "sesame-oil",
    "miso",
    "tofu",
    "green-onion",
    "rice-vinegar",
  ],
  indian: [
    "onion",
    "garlic",
    "ginger",
    "tomato",
    "cumin",
    "turmeric",
    "coriander",
    "garam-masala",
    "coconut-milk",
    "curry-leaves",
  ],
  thai: [
    "coconut-milk",
    "lime",
    "fish-sauce",
    "garlic",
    "ginger",
    "chili",
    "basil",
    "lemongrass",
    "rice",
    "cilantro",
  ],
  mediterranean: [
    "olive-oil",
    "tomato",
    "garlic",
    "lemon",
    "oregano",
    "feta",
    "cucumber",
    "olives",
    "onion",
    "bell-pepper",
  ],
  french: [
    "butter",
    "garlic",
    "onion",
    "thyme",
    "white-wine",
    "cream",
    "mushroom",
    "parsley",
    "shallot",
    "chicken",
  ],
};

export const allIngredients: Ingredient[] = [
  // Proteins
  { id: "chicken", name: "Chicken", category: "Proteins" },
  { id: "beef", name: "Beef", category: "Proteins" },
  { id: "pork", name: "Pork", category: "Proteins" },
  { id: "tofu", name: "Tofu", category: "Proteins" },
  { id: "eggs", name: "Eggs", category: "Proteins" },

  // Vegetables
  { id: "tomato", name: "Tomato", category: "Vegetables" },
  { id: "onion", name: "Onion", category: "Vegetables" },
  { id: "garlic", name: "Garlic", category: "Vegetables" },
  { id: "bell-pepper", name: "Bell Pepper", category: "Vegetables" },
  { id: "mushroom", name: "Mushroom", category: "Vegetables" },
  { id: "cucumber", name: "Cucumber", category: "Vegetables" },
  { id: "avocado", name: "Avocado", category: "Vegetables" },
  { id: "jalapeno", name: "Jalapeño", category: "Vegetables" },
  { id: "ginger", name: "Ginger", category: "Vegetables" },
  { id: "green-onion", name: "Green Onion", category: "Vegetables" },
  { id: "shallot", name: "Shallot", category: "Vegetables" },

  // Herbs & Spices
  { id: "basil", name: "Basil", category: "Herbs & Spices" },
  { id: "oregano", name: "Oregano", category: "Herbs & Spices" },
  { id: "cilantro", name: "Cilantro", category: "Herbs & Spices" },
  { id: "cumin", name: "Cumin", category: "Herbs & Spices" },
  { id: "turmeric", name: "Turmeric", category: "Herbs & Spices" },
  { id: "coriander", name: "Coriander", category: "Herbs & Spices" },
  { id: "garam-masala", name: "Garam Masala", category: "Herbs & Spices" },
  { id: "chili", name: "Chili", category: "Herbs & Spices" },
  { id: "thyme", name: "Thyme", category: "Herbs & Spices" },
  { id: "parsley", name: "Parsley", category: "Herbs & Spices" },
  { id: "lemongrass", name: "Lemongrass", category: "Herbs & Spices" },
  { id: "curry-leaves", name: "Curry Leaves", category: "Herbs & Spices" },

  // Pantry
  { id: "pasta", name: "Pasta", category: "Pantry" },
  { id: "rice", name: "Rice", category: "Pantry" },
  { id: "olive-oil", name: "Olive Oil", category: "Pantry" },
  { id: "soy-sauce", name: "Soy Sauce", category: "Pantry" },
  { id: "sesame-oil", name: "Sesame Oil", category: "Pantry" },
  { id: "coconut-milk", name: "Coconut Milk", category: "Pantry" },
  { id: "black-beans", name: "Black Beans", category: "Pantry" },
  { id: "butter", name: "Butter", category: "Pantry" },
  { id: "cream", name: "Cream", category: "Pantry" },
  { id: "miso", name: "Miso", category: "Pantry" },
  { id: "seaweed", name: "Seaweed", category: "Pantry" },
  { id: "olives", name: "Olives", category: "Pantry" },

  // Dairy & Cheese
  { id: "mozzarella", name: "Mozzarella", category: "Dairy & Cheese" },
  { id: "parmesan", name: "Parmesan", category: "Dairy & Cheese" },
  { id: "cheese", name: "Cheese", category: "Dairy & Cheese" },
  { id: "feta", name: "Feta", category: "Dairy & Cheese" },

  // Condiments & Acids
  { id: "lime", name: "Lime", category: "Condiments & Acids" },
  { id: "lemon", name: "Lemon", category: "Condiments & Acids" },
  { id: "fish-sauce", name: "Fish Sauce", category: "Condiments & Acids" },
  { id: "rice-vinegar", name: "Rice Vinegar", category: "Condiments & Acids" },
  { id: "white-wine", name: "White Wine", category: "Condiments & Acids" },
  { id: "mirin", name: "Mirin", category: "Condiments & Acids" },
];

