import mongoose, { Schema, Document } from "mongoose";

export interface IRecipe extends Document {
  name: string;
  description: string;
  cuisine: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  difficulty: string;
  ingredients: Array<{
    amount: string;
    item: string;
  }>;
  instructions: string[];
  tips: string[];
  // Metadata for tracking
  cuisines: string[]; // Array of cuisine IDs used
  ingredientIds: string[]; // Array of ingredient IDs used
  generatedBy: "ai" | "template";
  aiModel?: string; // AI model used if generated by AI
  createdAt?: Date;
  updatedAt?: Date;
}

const RecipeSchema = new Schema<IRecipe>(
  {
    name: {
      type: String,
      required: true,
      index: true,
    },
    description: {
      type: String,
      required: true,
    },
    cuisine: {
      type: String,
      required: true,
      index: true,
    },
    prepTime: {
      type: String,
      required: true,
    },
    cookTime: {
      type: String,
      required: true,
    },
    servings: {
      type: Number,
      required: true,
    },
    difficulty: {
      type: String,
      required: true,
      enum: ["Easy", "Medium", "Hard"],
    },
    ingredients: [
      {
        amount: { type: String, required: true },
        item: { type: String, required: true },
      },
    ],
    instructions: {
      type: [String],
      required: true,
      default: [],
    },
    tips: {
      type: [String],
      required: true,
      default: [],
    },
    cuisines: {
      type: [String],
      required: true,
    },
    ingredientIds: {
      type: [String],
      required: true,
    },
    generatedBy: {
      type: String,
      required: true,
      enum: ["ai", "template"],
      default: "ai",
    },
    aiModel: {
      type: String,
    },
  },
  {
    timestamps: true,
  }
);

// Individual indexes for searching recipes
// Note: Cannot use compound index on two array fields in MongoDB
RecipeSchema.index({ cuisines: 1 });
RecipeSchema.index({ ingredientIds: 1 });
RecipeSchema.index({ createdAt: -1 }); // For sorting by newest

export const Recipe = mongoose.model<IRecipe>("Recipe", RecipeSchema);

