import puppeteer from "puppeteer";
import { Recipe } from "../models/Recipe";

interface ShoppingListItem {
  name: string;
  amount: string;
  category: string;
  checked?: boolean;
}

interface RecipeData {
  name: string;
  description: string;
  cuisine: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  difficulty: string;
  ingredients: Array<{ amount: string; item: string }>;
  instructions: string[];
  tips?: string[];
}

export class PDFService {
  /**
   * Generate PDF for a shopping list
   */
  static async generateShoppingListPDF(
    items: ShoppingListItem[],
    title: string = "Shopping List"
  ): Promise<Buffer> {
    const grouped = this.groupByCategory(items);
    const categories = Object.keys(grouped).sort();

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              color: #333;
            }
            h1 {
              color: #2563eb;
              border-bottom: 3px solid #2563eb;
              padding-bottom: 10px;
              margin-bottom: 30px;
            }
            .category {
              margin-bottom: 30px;
              page-break-inside: avoid;
            }
            .category-title {
              font-size: 18px;
              font-weight: bold;
              color: #1e40af;
              margin-bottom: 10px;
              border-bottom: 2px solid #e5e7eb;
              padding-bottom: 5px;
            }
            .item {
              padding: 8px 0;
              font-size: 14px;
              border-bottom: 1px solid #f3f4f6;
            }
            .item-name {
              font-weight: 500;
            }
            .item-amount {
              color: #6b7280;
              margin-right: 10px;
            }
            .checked {
              text-decoration: line-through;
              color: #9ca3af;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 2px solid #e5e7eb;
              text-align: center;
              color: #6b7280;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          ${categories
            .map(
              (category) => `
            <div class="category">
              <div class="category-title">${category}</div>
              ${grouped[category]
                .map(
                  (item) => `
                <div class="item ${item.checked ? "checked" : ""}">
                  <span class="item-amount">${item.amount}</span>
                  <span class="item-name">${item.name}</span>
                </div>
              `
                )
                .join("")}
            </div>
          `
            )
            .join("")}
          <div class="footer">
            Generated by MealMind AI • ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `;

    return this.htmlToPDF(html);
  }

  /**
   * Generate PDF for a recipe
   */
  static async generateRecipePDF(recipe: RecipeData): Promise<Buffer> {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              color: #333;
              line-height: 1.6;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
              border-bottom: 3px solid #2563eb;
              padding-bottom: 20px;
            }
            h1 {
              color: #2563eb;
              font-size: 32px;
              margin-bottom: 10px;
            }
            .description {
              color: #6b7280;
              font-size: 16px;
              font-style: italic;
              margin-bottom: 20px;
            }
            .meta {
              display: flex;
              justify-content: center;
              gap: 30px;
              flex-wrap: wrap;
              margin-top: 20px;
            }
            .meta-item {
              display: flex;
              align-items: center;
              gap: 8px;
              color: #4b5563;
            }
            .badge {
              display: inline-block;
              padding: 4px 12px;
              border-radius: 12px;
              font-size: 12px;
              font-weight: 600;
              margin: 0 4px;
            }
            .badge-cuisine {
              background-color: #dbeafe;
              color: #1e40af;
            }
            .badge-difficulty {
              background-color: #fef3c7;
              color: #92400e;
            }
            .section {
              margin-top: 40px;
              page-break-inside: avoid;
            }
            .section-title {
              font-size: 24px;
              font-weight: bold;
              color: #1e40af;
              margin-bottom: 20px;
              border-bottom: 2px solid #e5e7eb;
              padding-bottom: 10px;
            }
            .ingredients-list {
              list-style: none;
              padding: 0;
            }
            .ingredient-item {
              padding: 10px 0;
              border-bottom: 1px solid #f3f4f6;
              display: flex;
              gap: 15px;
            }
            .ingredient-amount {
              font-weight: 600;
              color: #2563eb;
              min-width: 100px;
            }
            .instructions-list {
              list-style: none;
              padding: 0;
              counter-reset: step-counter;
            }
            .instruction-item {
              counter-increment: step-counter;
              padding: 15px 0;
              border-bottom: 1px solid #f3f4f6;
              padding-left: 50px;
              position: relative;
            }
            .instruction-item::before {
              content: counter(step-counter);
              position: absolute;
              left: 0;
              top: 15px;
              background-color: #2563eb;
              color: white;
              width: 30px;
              height: 30px;
              border-radius: 50%;
              display: flex;
              align-items: center;
              justify-content: center;
              font-weight: bold;
              font-size: 14px;
            }
            .tips-list {
              list-style: none;
              padding: 0;
            }
            .tip-item {
              padding: 10px 0;
              padding-left: 25px;
              position: relative;
            }
            .tip-item::before {
              content: "💡";
              position: absolute;
              left: 0;
            }
            .footer {
              margin-top: 60px;
              padding-top: 20px;
              border-top: 2px solid #e5e7eb;
              text-align: center;
              color: #6b7280;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${recipe.name}</h1>
            <div class="description">${recipe.description}</div>
            <div class="meta">
              <div class="meta-item">
                <span>⏱️</span>
                <span>Prep: ${recipe.prepTime}</span>
              </div>
              <div class="meta-item">
                <span>🔥</span>
                <span>Cook: ${recipe.cookTime}</span>
              </div>
              <div class="meta-item">
                <span>👥</span>
                <span>Serves: ${recipe.servings}</span>
              </div>
            </div>
            <div style="margin-top: 15px;">
              <span class="badge badge-cuisine">${recipe.cuisine}</span>
              <span class="badge badge-difficulty">${recipe.difficulty}</span>
            </div>
          </div>

          <div class="section">
            <div class="section-title">Ingredients</div>
            <ul class="ingredients-list">
              ${recipe.ingredients
                .map(
                  (ing) => `
                <li class="ingredient-item">
                  <span class="ingredient-amount">${ing.amount}</span>
                  <span>${ing.item}</span>
                </li>
              `
                )
                .join("")}
            </ul>
          </div>

          <div class="section">
            <div class="section-title">Instructions</div>
            <ol class="instructions-list">
              ${recipe.instructions
                .map(
                  (instruction) => `
                <li class="instruction-item">${instruction}</li>
              `
                )
                .join("")}
            </ol>
          </div>

          ${
            recipe.tips && recipe.tips.length > 0
              ? `
            <div class="section">
              <div class="section-title">Chef's Tips</div>
              <ul class="tips-list">
                ${recipe.tips
                  .map(
                    (tip) => `
                  <li class="tip-item">${tip}</li>
                `
                  )
                  .join("")}
              </ul>
            </div>
          `
              : ""
          }

          <div class="footer">
            Generated by MealMind AI • ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `;

    return this.htmlToPDF(html);
  }

  /**
   * Group shopping list items by category
   */
  private static groupByCategory(
    items: ShoppingListItem[]
  ): Record<string, ShoppingListItem[]> {
    return items.reduce((acc, item) => {
      if (!acc[item.category]) {
        acc[item.category] = [];
      }
      acc[item.category].push(item);
      return acc;
    }, {} as Record<string, ShoppingListItem[]>);
  }

  /**
   * Convert HTML to PDF using Puppeteer
   */
  private static async htmlToPDF(html: string): Promise<Buffer> {
    let browser;
    try {
      browser = await puppeteer.launch({
        headless: true,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-gpu",
          "--disable-software-rasterizer",
        ],
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH, // Allow override via env var
      });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });
      const pdf = await page.pdf({
        format: "A4",
        margin: {
          top: "20mm",
          right: "15mm",
          bottom: "20mm",
          left: "15mm",
        },
        printBackground: true,
      });
      return Buffer.from(pdf);
    } catch (error) {
      console.error("Error generating PDF:", error);
      
      // Provide helpful error message for Chrome launch failures
      if (error instanceof Error && error.message.includes("Failed to launch")) {
        throw new Error(
          "PDF generation failed: Chrome browser not available. " +
          "Please run 'pnpm fix-chrome' in the server directory to reinstall Chrome."
        );
      }
      
      throw new Error("Failed to generate PDF");
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }
}
